[%
    T = {
        configure_1                                = "IntranetUserJS: Set Koha fields/checkboxes defaults Configuration",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Set defaults for Koha fields and checkboxes &rsaquo; Configuration",
        configure_5                                = "Check the box \"Cancel holds fees\" during return.",
        configure_6                                = "This prevents an unclaimed hold fee from being generated when a hold waiting to be picked up is canceled via return.",
        configure_7                                = "Note! This does not work if the return is done anywhere else than on the Returns page.",
        configure_8                                = "Set the default language choice for patron notices to Finnish.",
        configure_9                                = "Check the box \"Delete record if no items remaining\" in batch item deletion. This ensures that records without items are not left in the database.",
        configure_10                               = "Set the logged-in library as the default library for serials receipt.",
        configure_11                               = "Preselect the Relationship value in the patron guarantor section.",
        configure_12                               = "Save configuration",
        configure_13                               = "Upgrade status",
        configure_14                               = "Plugin has never been upgraded.",
        viewjs_1                                   = "IntranetUserJS: Set Koha fields/checkboxes defaults",
        viewjs_2                                   = "&rsaquo; SetDefaults &rsaquo; View JS Tool",
    }
%]