[%
    T = {
        configure_1  = "Home",
        configure_2  = "Plugins",
        configure_3  = "&rsaquo; IntranetUserJS: Set defaults for Koha fields and checkboxes &rsaquo; Configuration",
        configure_4  = "Set patron's primary contact method to 'email' by default on the patron add/edit form.",
        configure_5  = "The primary contact method setting is required if the patron category enforces expiration notices. In this case, notices about the expiring account will be sent according to the selected contact method.",
        configure_6  = "Hide the patron's primary contact method field on the patron add/edit form.",
        configure_7  = "IntranetUserJS: Set defaults for Koha fields and checkboxes - Configuration",
        configure_8  = "Check the \"Cancel holds with fees\" checkbox during return.",
        configure_9  = "This prevents a fee from being generated for an uncollected hold when a hold available for pickup is cancelled via return.",
        configure_10 = "Note! Does not work if the return is done anywhere else than on the Returns page.",
        configure_11 = "Set default language choice for notices sent to the patron to Finnish.",
        configure_12 = "Check the \"Delete records if all items are deleted\" checkbox in batch item deletion. This ensures that no records without items are left in the database.",
        configure_13 = "Set the logged-in library as the default library for serials check-in.",
        configure_14 = "Set the Relationship value in the patron guarantor section by default.",
        configure_15 = "Save configuration",
        configure_16 = "Upgrade status",
        configure_17 = "The plugin has never been upgraded.",
        viewjs_1     = "IntranetUserJS: Set defaults for Koha fields and checkboxes",
        viewjs_2     = "&rsaquo; SetDefaults &rsaquo; View JS Tool",
    }
%]