[%
    T = {
        configure_1                                = "IntranetUserJS: Aseta oletusarvot Koha-kentille ja valintaruuduille -asetukset",
        configure_2                                = "Etusivu",
        configure_3                                = "Liitännäiset",
        configure_4                                = "&rsaquo; IntranetUserJS: Aseta oletusarvot Koha-kentille ja valintaruuduille &rsaquo; Asetukset",
        configure_5                                = "Laita raksi \"Poista käsin poistettujen varausten maksut\" -kohtaan palautuksessa.",
        configure_6                                = "Tällä estetään noutamattoman varauksen maksun syntyminen, kun noudettavissa oleva varaus poistetaan palautuksen kautta.",
        configure_7                                = "Huom! Ei toimi, jos palautus tehdään muualla kuin Palautus-sivulla.",
        configure_8                                = "Asiakkaalle lähtevien ilmoitusten oletuskielivalinta suomeksi.",
        configure_9                                = "Laita niteiden eräpoistossa raksi kohtaan \"Poista tietueet, jos kaikki niteet poistettu\". Tällä varmistetaan, että tietokantaan ei jää niteettömiä tietueita.",
        configure_10                               = "Kausijulkaisujen vastaanoton oletuskirjastoksi kirjautumiskirjasto.",
        configure_11                               = "Asiakastakaaja-osion Suhde-arvo valmiiksi valituksi.",
        configure_12                               = "Tallenna asetukset",
        configure_13                               = "Päivityksen tila",
        configure_14                               = "Liitännäistä ei ole koskaan päivitetty.",
        viewjs_1                                   = "IntranetUserJS: Aseta oletusarvot Koha-kentille ja valintaruuduille",
        viewjs_2                                   = "&rsaquo; SetDefaults &rsaquo; Näytä JS-työkalu",
    }
%]