[%
    T = {
        configure_1  = "Etusivu",
        configure_2  = "Liitännäiset",
        configure_3  = "&rsaquo; IntranetUserJS: Aseta oletusarvot Koha-kentille ja valintaruuduille &rsaquo; Asetukset",
        configure_4  = "Asiakkaan ensisijainen yhteydenottotapa 'email' valmiiksi valituksi asiakkaan lisäys/muokkauslomakkeella.",
        configure_5  = "Asiakkaan ensisijainen yhteydenottotapa-asetusta tarvitaan, jos asiakastyypille on pakotettu vanhenemisilmoitusten lähettäminen. Tällöin ilmoitukset vanhenevasta asiakastilistä lähetetään valitun yhteydenottotavan mukaisesti.",
        configure_6  = "Piilota Asiakkaan ensisijainen yhteydenottotapa-kenttä asiakastietojen lisäys/muokkauslomakkeella.",
        configure_7  = "IntranetUserJS: Aseta oletusarvot Koha-kentille ja valintaruuduille -asetukset",
        configure_8  = "Laita raksi \"Poista käsin poistettujen varausten maksut\" -kohtaan palautuksessa.",
        configure_9  = "Tällä estetään noutamattoman varauksen maksun syntyminen, kun noudettavissa oleva varaus poistetaan palautuksen kautta.",
        configure_10 = "Huom! Ei toimi, jos palautus tehdään muualla kuin Palautus-sivulla.",
        configure_11 = "Asiakkaalle lähtevien ilmoitusten oletuskielivalinta suomeksi.",
        configure_12 = "Laita niteiden eräpoistossa raksi kohtaan \"Poista tietueet, jos kaikki niteet poistettu\". Tällä varmistetaan, että tietokantaan ei jää niteettömiä tietueita.",
        configure_13 = "Kausijulkaisujen vastaanoton oletuskirjastoksi kirjautumiskirjasto.",
        configure_14 = "Asiakastakaaja-osion Suhde-arvo valmiiksi valituksi.",
        configure_15 = "Tallenna asetukset",
        configure_16 = "Päivityksen tila",
        configure_17 = "Liitännäistä ei ole koskaan päivitetty.",
        viewjs_1     = "IntranetUserJS: Aseta oletusarvot Koha-kentille ja valintaruuduille",
        viewjs_2     = "&rsaquo; SetDefaults &rsaquo; Näytä JS-työkalu",
    }
%]