[%
    T = {
        configure_1                                = "IntranetUserJS: Ange standardvärden för Koha-fält och kryssrutor-inställningar",
        configure_2                                = "Hem",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Ange standardvärden för Koha-fält och kryssrutor &rsaquo; Inställningar",
        configure_5                                = "Kryssa i rutan \"Avbryt reservationsavgifter\" vid återlämning.",
        configure_6                                = "Detta förhindrar att en avgift för outhämtad reservation skapas när en reservation som väntar på avhämtning avbryts via återlämning.",
        configure_7                                = "Obs! Fungerar inte om återlämningen görs någon annanstans än på sidan Återlämna.",
        configure_8                                = "Förvalt språkval för meddelanden till låntagare till finska.",
        configure_9                                = "Kryssa i rutan \"Ta bort posten om inga exemplar återstår\" vid gallring av exemplar. Detta säkerställer att poster utan exemplar inte lämnas kvar i databasen.",
        configure_10                               = "Sätt den inloggade databasen/biblioteket som förvalt bibliotek för tidskriftsmottagning.",
        configure_11                               = "Välj relationsvärdet i låntagargarantisektionen i förväg.",
        configure_12                               = "Spara inställningar",
        configure_13                               = "Uppgraderingsstatus",
        configure_14                               = "Pluginet har aldrig uppgraderats.",
        viewjs_1                                   = "IntranetUserJS: Ange standardvärden för Koha-fält och kryssrutor",
        viewjs_2                                   = "&rsaquo; SetDefaults &rsaquo; Visa JS-verktyg",
    }
%]