[%
    T = {
        configure_1  = "Hem",
        configure_2  = "Plugins",
        configure_3  = "&rsaquo; IntranetUserJS: Ange standardvärden för Koha-fält och kryssrutor &rsaquo; Konfiguration",
        configure_4  = "Välj automatiskt 'epost' som låntagarens primära kontaktsätt på formuläret för att lägga till/redigera låntagare.",
        configure_5  = "Inställningen för primärt kontaktsätt krävs om meddelanden om förfallna konton är tvingande för låntagarkategorin. I så fall skickas meddelanden om det utgående kontot enligt det valda kontaktsättet.",
        configure_6  = "Dölj fältet för låntagarens primära kontaktsätt på formuläret för att lägga till/redigera låntagare.",
        configure_7  = "IntranetUserJS: Ange standardvärden för Koha-fält och kryssrutor - Inställningar",
        configure_8  = "Kryssa i rutan \"Ta bort avgifter för makulerade reservationer\" vid återlämning.",
        configure_9  = "Detta förhindrar att en avgift uppstår för en ej avhämtad reservation när en tillgänglig reservation makuleras via återlämning.",
        configure_10 = "Obs! Fungerar inte om återlämningen görs någon annanstans än på återlämningssidan.",
        configure_11 = "Ställ in standardspråkvalet för meddelanden till låntagaren på finska.",
        configure_12 = "Kryssa i rutan \"Ta bort poster om alla exemplar raderas\" vid batchradering av exemplar. Detta säkerställer det inte lämnas kvar poster utan exemplar i databasen.",
        configure_13 = "Ställ in den inloggade databasen som standardbibliotek vid mottagning av tidskrifter.",
        configure_14 = "Välj automatiskt värdet för Relation i sektionen för låntagargarant.",
        configure_15 = "Spara inställningar",
        configure_16 = "Uppgraderingsstatus",
        configure_17 = "Insticksprogrammet har aldrig uppgraderats.",
        viewjs_1     = "IntranetUserJS: Ange standardvärden för Koha-fält och kryssrutor",
        viewjs_2     = "&rsaquo; SetDefaults &rsaquo; Visa JS-verktyg",
    }
%]